//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.CustomTables;
using CMS.CustomTables.Types.Statiq;

[assembly: RegisterCustomTable(RatingsItem.CLASS_NAME, typeof(RatingsItem))]

namespace CMS.CustomTables.Types.Statiq
{
	/// <summary>
	/// Represents a content item of type RatingsItem.
	/// </summary>
	public partial class RatingsItem : CustomTableItem
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "statiq.ratings";


		/// <summary>
		/// The instance of the class that provides extended API for working with RatingsItem fields.
		/// </summary>
		private readonly RatingsItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// Username.
		/// </summary>
		[DatabaseField]
		public string UserName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("UserName"), @"");
			}
			set
			{
				SetValue("UserName", value);
			}
		}


		/// <summary>
		/// Book.
		/// </summary>
		[DatabaseField]
		public int Book
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("Book"), 0);
			}
			set
			{
				SetValue("Book", value);
			}
		}


		/// <summary>
		/// Rating.
		/// </summary>
		[DatabaseField]
		public int Rating
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("Rating"), 0);
			}
			set
			{
				SetValue("Rating", value);
			}
		}


		/// <summary>
		/// Comment.
		/// </summary>
		[DatabaseField]
		public string Comment
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Comment"), @"");
			}
			set
			{
				SetValue("Comment", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with RatingsItem fields.
		/// </summary>
		[RegisterProperty]
		public RatingsItemFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with RatingsItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class RatingsItemFields : AbstractHierarchicalObject<RatingsItemFields>
		{
			/// <summary>
			/// The content item of type RatingsItem that is a target of the extended API.
			/// </summary>
			private readonly RatingsItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="RatingsItemFields" /> class with the specified content item of type RatingsItem.
			/// </summary>
			/// <param name="instance">The content item of type RatingsItem that is a target of the extended API.</param>
			public RatingsItemFields(RatingsItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// Username.
			/// </summary>
			public string UserName
			{
				get
				{
					return mInstance.UserName;
				}
				set
				{
					mInstance.UserName = value;
				}
			}


			/// <summary>
			/// Book.
			/// </summary>
			public int Book
			{
				get
				{
					return mInstance.Book;
				}
				set
				{
					mInstance.Book = value;
				}
			}


			/// <summary>
			/// Rating.
			/// </summary>
			public int Rating
			{
				get
				{
					return mInstance.Rating;
				}
				set
				{
					mInstance.Rating = value;
				}
			}


			/// <summary>
			/// Comment.
			/// </summary>
			public string Comment
			{
				get
				{
					return mInstance.Comment;
				}
				set
				{
					mInstance.Comment = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="RatingsItem" /> class.
		/// </summary>
		public RatingsItem() : base(CLASS_NAME)
		{
			mFields = new RatingsItemFields(this);
		}

		#endregion
	}
}