//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Statiq;

[assembly: RegisterDocumentType(Author.CLASS_NAME, typeof(Author))]

namespace CMS.DocumentEngine.Types.Statiq
{
	/// <summary>
	/// Represents a content item of type Author.
	/// </summary>
	public partial class Author : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Statiq.Author";


		/// <summary>
		/// The instance of the class that provides extended API for working with Author fields.
		/// </summary>
		private readonly AuthorFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// AuthorID.
		/// </summary>
		[DatabaseIDField]
		public int AuthorID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("AuthorID"), 0);
			}
			set
			{
				SetValue("AuthorID", value);
			}
		}


		/// <summary>
		/// First name.
		/// </summary>
		[DatabaseField]
		public string FirstName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("FirstName"), @"");
			}
			set
			{
				SetValue("FirstName", value);
			}
		}


		/// <summary>
		/// Last name.
		/// </summary>
		[DatabaseField]
		public string LastName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("LastName"), @"");
			}
			set
			{
				SetValue("LastName", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with Author fields.
		/// </summary>
		[RegisterProperty]
		public AuthorFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with Author fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class AuthorFields : AbstractHierarchicalObject<AuthorFields>
		{
			/// <summary>
			/// The content item of type Author that is a target of the extended API.
			/// </summary>
			private readonly Author mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="AuthorFields" /> class with the specified content item of type Author.
			/// </summary>
			/// <param name="instance">The content item of type Author that is a target of the extended API.</param>
			public AuthorFields(Author instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// AuthorID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.AuthorID;
				}
				set
				{
					mInstance.AuthorID = value;
				}
			}


			/// <summary>
			/// First name.
			/// </summary>
			public string FirstName
			{
				get
				{
					return mInstance.FirstName;
				}
				set
				{
					mInstance.FirstName = value;
				}
			}


			/// <summary>
			/// Last name.
			/// </summary>
			public string LastName
			{
				get
				{
					return mInstance.LastName;
				}
				set
				{
					mInstance.LastName = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="Author" /> class.
		/// </summary>
		public Author() : base(CLASS_NAME)
		{
			mFields = new AuthorFields(this);
		}

		#endregion
	}
}