//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Statiq;

[assembly: RegisterDocumentType(ContactUs.CLASS_NAME, typeof(ContactUs))]

namespace CMS.DocumentEngine.Types.Statiq
{
	/// <summary>
	/// Represents a content item of type ContactUs.
	/// </summary>
	public partial class ContactUs : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Statiq.ContactUs";


		/// <summary>
		/// The instance of the class that provides extended API for working with ContactUs fields.
		/// </summary>
		private readonly ContactUsFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// ContactUsID.
		/// </summary>
		[DatabaseIDField]
		public int ContactUsID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("ContactUsID"), 0);
			}
			set
			{
				SetValue("ContactUsID", value);
			}
		}


		/// <summary>
		/// Location.
		/// </summary>
		[DatabaseField]
		public string Location
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Location"), @"");
			}
			set
			{
				SetValue("Location", value);
			}
		}


		/// <summary>
		/// Google Maps embed URL.
		/// </summary>
		[DatabaseField]
		public string MapUrl
		{
			get
			{
				return ValidationHelper.GetString(GetValue("MapUrl"), @"");
			}
			set
			{
				SetValue("MapUrl", value);
			}
		}


		/// <summary>
		/// Email.
		/// </summary>
		[DatabaseField]
		public string Email
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Email"), @"");
			}
			set
			{
				SetValue("Email", value);
			}
		}


		/// <summary>
		/// Phone.
		/// </summary>
		[DatabaseField]
		public string Phone
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Phone"), @"");
			}
			set
			{
				SetValue("Phone", value);
			}
		}


		/// <summary>
		/// Message.
		/// </summary>
		[DatabaseField]
		public string Message
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Message"), @"");
			}
			set
			{
				SetValue("Message", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with ContactUs fields.
		/// </summary>
		[RegisterProperty]
		public ContactUsFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with ContactUs fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class ContactUsFields : AbstractHierarchicalObject<ContactUsFields>
		{
			/// <summary>
			/// The content item of type ContactUs that is a target of the extended API.
			/// </summary>
			private readonly ContactUs mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="ContactUsFields" /> class with the specified content item of type ContactUs.
			/// </summary>
			/// <param name="instance">The content item of type ContactUs that is a target of the extended API.</param>
			public ContactUsFields(ContactUs instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// ContactUsID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.ContactUsID;
				}
				set
				{
					mInstance.ContactUsID = value;
				}
			}


			/// <summary>
			/// Location.
			/// </summary>
			public string Location
			{
				get
				{
					return mInstance.Location;
				}
				set
				{
					mInstance.Location = value;
				}
			}


			/// <summary>
			/// Google Maps embed URL.
			/// </summary>
			public string MapUrl
			{
				get
				{
					return mInstance.MapUrl;
				}
				set
				{
					mInstance.MapUrl = value;
				}
			}


			/// <summary>
			/// Email.
			/// </summary>
			public string Email
			{
				get
				{
					return mInstance.Email;
				}
				set
				{
					mInstance.Email = value;
				}
			}


			/// <summary>
			/// Phone.
			/// </summary>
			public string Phone
			{
				get
				{
					return mInstance.Phone;
				}
				set
				{
					mInstance.Phone = value;
				}
			}


			/// <summary>
			/// Message.
			/// </summary>
			public string Message
			{
				get
				{
					return mInstance.Message;
				}
				set
				{
					mInstance.Message = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="ContactUs" /> class.
		/// </summary>
		public ContactUs() : base(CLASS_NAME)
		{
			mFields = new ContactUsFields(this);
		}

		#endregion
	}
}