name: Statiq CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Deploy
      run: dotnet run -- deploy
      env:
        CMSConnectionString: ${{ secrets.CMSConnectionString }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
