name: Statiq CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:

    runs-on: windows-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build
      run: dotnet run
      env:
        CMSConnectionString: ${{ secrets.CMSConnectionString }}
    - name: Deploy to GitHub
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.personal_token }}
        external_repository: kentico-ericd/kentico-ericd.github.io
        publish_branch: master
        publish_dir: ./output
